title: Susan G. Fink
description: Sharing Life. Staying Consistent.
url: "https://susangfink.com/"
baseurl: ""
logo: /images/susangfink-logo.jpg

google_analytics: G-R445NTQBQN
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from

collections:
  blog: 
    output: true
    permalink: "/blog/:year/:month/:day/:title/"
  recipes:
    output: true
    permalink: "/recipes/:title/"
  travel:
    output: true
    permalink: "/travel/:title/"
  reflections:
    ouput: true
    permalink: "/reflections/:title/"
  family:
    output: true
    permalink: "/family/:title/"
  health:
    output: true
    permalink: "/health/:title/"
  house:
    output: true
    permalink: "/house/:title/"

footer_links:
  - title: Instagram
    url: https://instagram.com/susanfink
    icon: fab fa-instagram

markdown: kramdown

paginate: 10
paginate_path: "/blog/page:num/"
