title: Susan G. Fink
description: Sharing Life. Staying Consistent.
url: "https://susangfink.com/"
baseurl: "/site"
logo: /images/susangfink-logo.jpg
# remote_theme: mmistakes/so-simple-theme

google_analytics: G-R445NTQBQN
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  recipes:
    output: true
    permalink: /recipes/:title/

markdown: kramdown
