title: Susan G. Fink
description: Sharing Life. Staying Consistent.
url: "https://susangfink.github.io"
baseurl: "/site"
logo: /images/susangfink-logo.jpg
remote_theme: mmistakes/so-simple-theme

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  recipes:
    output: true
    permalink: /recipes/:title/

markdown: kramdown
