title: Susan G. Fink
description: Sharing Life. Staying Consistent.
url: "https://susangfink.com/"
baseurl: ""
logo: /images/susangfink-logo.jpg

google_analytics: G-R445NTQBQN
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-paginate-v2
  - jekyll-redirect-from

collections:
  blog: 
    output: true
    permalink: "/blog/:year/:month/:day/:title/"
  recipes:
    output: true
    permalink: "/recipes/:title/"
  travel:
    output: true
    permalink: "/travel/:title/"
  family:
    output: true
    permalink: "/family/:title/"
  health:
    output: true
    permalink: "/health/:title/"
  house:
    output: true
    permalink: "/house/:title/"

footer_links:
  - title: Instagram
    url: https://instagram.com/susanfink
    icon: fab fa-instagram

markdown: kramdown

paginate: 3
paginate_path: "/blog/page:num/"

pagination:
  enabled: true
  per_page: 3
  permalink: '/category/:name/page/:num/'
  title: ':title - page :num'
  trail:
    before: 2
    after: 2
    
