title: Susan G. Fink
description: A simple, intentional life journal
url: "https://susangfink.github.io"
baseurl: "/site"
logo: /images/SusanGFink.jpg
remote_theme: mmistakes/so-simple-theme

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
