title: Susan G. Fink
description: Sharing Life. Staying Consistent.
url: "https://susangfink.com/"
baseurl: ""
logo: /images/susangfink-logo.jpg

google_analytics: G-R445NTQBQN
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from

collections:
  blog: 
    output: true
    permalink: "/blog/:year/:month/:day/:title/"
  recipes:
    output: true
    permalink: "/recipes/:title/"

footer_links:
  - title: Instagram
    url: https://instagram.com/susanfink
    icon: fab fa-instagram

markdown: kramdown

paginate: 3
paginate_path: "/blog/page:num/"

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1

    - name: "Blog"
      identifier: "blog"
      url: "#"
      weight: 10

    - name: "House"
      parent: "blog"
      url: "/blog/house/"
      weight: 11

    - name: "Health"
      parent: "blog"
      url: "/blog/health/"
      weight: 12

    - name: "Family"
      parent: "blog"
      url: "/blog/family/"
      weight: 13

    - name: "Food"
      parent: "blog"
      url: "/blog/food/"
      weight: 14

    - name: "Travel"
      parent: "blog"
      url: "/blog/travel/"
      weight: 15

    - name: "Reflections"
      parent: "blog"
      url: "/blog/reflections/"
      weight: 16

    - name: "About"
      url: "/about/"
      weight: 20
